### ISSUE TITLE
Issue running unit test

### ISSUE THREAD

**Issue by fulviopp** [aichaos/rivescript-python#17]
Hi,

When I'm trying to run de unit test, for all of them I receive AssertionError and the message = "**[ERR: No default topic 'random' was found!]**", example:

```
Failure
Traceback (most recent call last):
  File "/Users/fuvio/Documents/jarvis/jarvis/tests/test_script.py", line 30, in test_no_begin_block
    self.reply("Hello bot", "Hello human.")
  File "/Users/fuvio/Documents/jarvis/jarvis/tests/config.py", line 35, in reply
    self.assertEqual(reply, expected)
AssertionError: "[ERR: No default topic 'random' was found!]" != u'Hello human.'
```

I'm running in python 2.7.9, could be this the problem?

Thanks in advance!

**Comment by kirsle** [comment]
Are you running the tests with `nosetests`? It works for me on a fresh checkout of this git repo.

```bash
$ mkvirtualenv sandbox
(sandbox)$ pip install nose
Collecting nose
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
    100% |################################| 155kB 2.4MB/s 
Installing collected packages: nose

Successfully installed nose-1.3.7
(sandbox)$ nosetests
........................
----------------------------------------------------------------------
Ran 24 tests in 0.072s

OK
(sandbox)$ python --version
Python 2.7.10
```

**Comment by fulviopp** [comment]
Thanks, kirsle! I wasn't using nosetests, with them it works fine.
